const fs = require('fs');

const bl = JSON.parse(fs.readFileSync('C:/Users/roika/Desktop/BaseVV/hoved/locales/bl.json','utf8'));
const eb = JSON.parse(fs.readFileSync('C:/Users/roika/Desktop/BaseVV/scripts/english_bodies.json','utf8'));

// Bengali-Latin translation dictionary
const dict = {
  'the': '', 'a': '', 'an': '', 'is': 'hoy', 'are': 'hoye', 'was': 'chilo', 'were': 'chilo',
  'be': 'hote', 'been': 'hoyeche', 'being': 'hoya',
  'has': 'ache', 'have': 'ache', 'had': 'chilo',
  'do': 'kore', 'does': 'kore', 'did': 'korechilo', 'done': 'kora', 'doing': 'korche',
  'can': 'pare', 'could': 'paret', 'will': 'hobe', 'would': 'hoto', 'shall': 'hobe',
  'may': 'pete', 'might': 'peto', 'must': 'hobei',
  'not': 'na', 'no': 'na', 'nor': 'na', 'neither': 'na',
  'and': 'ebong', 'or': 'ba', 'but': 'kintu', 'yet': 'tou', 'so': 'tai',
  'if': 'jodi', 'then': 'tahole', 'else': 'nahole', 'than': 'theke',
  'as': 'hisebe', 'like': 'moto', 'such': 'erokom',
  'this': 'ei', 'that': 'oi', 'these': 'ei', 'those': 'oi',
  'it': 'eta', 'its': 'tar', 'itself': 'nijei',
  'he': 'se', 'she': 'se', 'they': 'tara', 'them': 'tader', 'their': 'tader',
  'we': 'amra', 'us': 'amader', 'our': 'amader',
  'you': 'apni', 'your': 'apnar',
  'who': 'je', 'whom': 'jake', 'which': 'je', 'what': 'ki',
  'all': 'sob', 'every': 'prithiti', 'each': 'prottek', 'both': 'dui',
  'some': 'kono', 'any': 'kono', 'many': 'onek', 'much': 'onek', 'more': 'aro',
  'few': 'kom', 'several': 'onek',
  'other': 'onno', 'another': 'onno', 'others': 'onnera',
  'also': 'o', 'too': 'o', 'very': 'khub', 'quite': 'beshi',
  'only': 'shudhu', 'just': 'shudhu', 'still': 'ekhono',
  'now': 'ekhon', 'today': 'aaj',
  'here': 'ekhane', 'there': 'okhane', 'where': 'kothay',
  'about': 'somporke', 'above': 'upore', 'after': 'por', 'again': 'abar',
  'against': 'birudhe', 'around': 'charidike',
  'before': 'age', 'behind': 'pichone', 'below': 'niche',
  'between': 'modhye', 'beyond': 'baaire',
  'during': 'somoy', 'except': 'charai',
  'for': 'jonno', 'from': 'theke', 'inside': 'bhitore',
  'into': 'e', 'near': 'kache',
  'off': 'band', 'out': 'baire',
  'through': 'diye', 'under': 'niche', 'without': 'chara',
  'off': 'band', 'out': 'baire',
  'through': 'diye', 'under': 'niche',
  'without': 'chara',
  'zero': 'shunno', 'one': 'ek', 'two': 'dui', 'three': 'tin', 'four': 'char',
  'five': 'pach', 'six': 'chhay', 'seven': 'shat', 'eight': 'at', 'nine': 'noy',
  'ten': 'dosh',
  'first': 'prothom', 'second': 'ditiyo', 'third': 'tritiyo',
  'last': 'shesh', 'next': 'poroborti', 'previous': 'purboborti',
  'bangladesh': 'Bangladesh',
  'bangla': 'Bangla', 'bengali': 'Bangali', 'bengalis': 'Bangali',
  'india': 'Bharat', 'indian': 'Bharatiyo',
  'pakistan': 'Pakistan', 'pakistani': 'Pakistani',
  'china': 'China', 'chinese': 'Chinese',
  'soviet union': 'Soviet Sangh', 'soviet': 'Soviet',
  'russia': 'Russia', 'russian': 'Russian',
  'america': 'Amerika', 'american': 'Amerikan',
  'dhaka': 'Dhaka',
  'west pakistan': 'Pashchim Pakistan', 'west pakistani': 'Pashchim Pakistani',
  'south asia': 'Dokkhin Asia', 'south asian': 'Dokkhin Ashiyo',
  'vanga vitanastika': 'Vanga Vitanastika',
  'nixon': 'Presiddent Nixon', 'modi': 'Pradhanmontri Modi',
  'awami league': 'Awami League',
  'operation searchlight': 'Operation Searchlight',
  'operation chengiz khan': 'Operation Chengiz Khan',
  'uss enterprise': 'USS Enterprise',
  'task force 74': 'Task Force 74',
  'gwadar': 'Gwadar',
  'cpec': 'CPEC',
  'islamabad': 'Islamabad',
  'new delhi': 'New Delhi', 'kabul': 'Kabul',
  'beijing': 'Beijing', 'washington': 'Washington',
  'moscow': 'Moscow', 'kremlin': 'Kremlin',
  'secular': 'dhormoniropekho', 'secularism': 'dhormoniropekota',
  'democracy': 'ganotontro', 'democratic': 'ganotantrik',
  'republic': 'projatontro',
  'independence': 'swadhinota', 'liberation': 'mukti',
  'identity': 'porichoy', 'culture': 'shongskriti', 'cultural': 'shongskritik',
  'society': 'samaj', 'social': 'samajik',
  'political': 'rajnoitik', 'economic': 'orthonoitik',
  'economy': 'orthoniti',
  'military': 'sainik', 'civil': 'asainik',
  'government': 'sorkar', 'state': 'rajyo',
  'nation': 'jati', 'country': 'desh',
  'power': 'shokti', 'rights': 'odhikar',
  'freedom': 'swadhinota', 'law': 'ain', 'legal': 'ainik',
  'constitution': 'shongbidhan', 'constitutional': 'shongbidhanik',
  'war': 'juddho', 'peace': 'shanti',
  'conflict': 'dwandwo', 'crisis': 'sankat',
  'violence': 'himsha', 'army': 'sena',
  'soldiers': 'sainik', 'general': 'senapoti',
  'president': 'rashtropoti', 'prime minister': 'pradhanmontri',
  'leader': 'neta', 'leadership': 'netritto',
  'elite': 'obhijat', 'election': 'nirbachon',
  'vote': 'bhoto', 'majority': 'shongkhogoristho',
  'minority': 'shongkhalpon', 'population': 'jonggon',
  'people': 'manush', 'community': 'goshti',
  'religious': 'dhormiyo', 'religion': 'dhormo',
  'islam': 'Islam', 'muslim': 'Muslim', 'hindu': 'Hindu',
  'atheism': 'nastikota', 'atheist': 'nastik',
  'believer': 'bishwasi', 'belief': 'bishwash', 'faith': 'bishwash',
  'god': 'ishshor',
  'world': 'duniya', 'worldview': 'drishtibhongi',
  'life': 'jibon', 'death': 'mrityu',
  'time': 'somoy', 'year': 'bochhor', 'years': 'bochhor',
  'day': 'din', 'days': 'din',
  'history': 'itihas', 'historical': 'aitihashik',
  'present': 'bortoman', 'past': 'atit', 'future': 'bhabishshot',
  'modern': 'adhunik', 'traditional': 'riti',
  'ancient': 'prachin', 'old': 'purono', 'new': 'notun',
  'big': 'boro', 'small': 'choto', 'large': 'boro',
  'great': 'mahan', 'important': 'guruttopurno',
  'major': 'prodhan', 'minor': 'shoman',
  'main': 'mul', 'primary': 'prothomik', 'secondary': 'ditiyo',
  'basic': 'mul', 'complex': 'jotil', 'simple': 'sahoj',
  'difficult': 'kothin', 'easy': 'sahoj',
  'possible': 'sombhob', 'impossible': 'osombhob',
  'necessary': 'dorkar',
  'absolute': 'puro', 'complete': 'sompurno', 'total': 'sompurno',
  'full': 'puro', 'entire': 'sompurno',
  'public': 'jonno sodagog', 'private': 'byaktigoto', 'personal': 'byaktigoto',
  'individual': 'byakti',
  'organization': 'songstha', 'institution': 'protishthan',
  'system': 'byabostha', 'structure': 'gathan',
  'framework': 'kathamo', 'process': 'prokriya',
  'strategy': 'koushol', 'policy': 'niti',
  'project': 'prokolpo', 'goal': 'laksho', 'purpose': 'uddesho',
  'result': 'fol', 'outcome': 'fol',
  'effect': 'prabhab', 'impact': 'prabhab',
  'change': 'poriborton', 'development': 'unnoyon',
  'growth': 'briddhi', 'progress': 'unnotti',
  'decline': 'obonoti',
  'help': 'sahajjo', 'aid': 'sahajjo',
  'resistance': 'protirodh', 'struggle': 'songram',
  'victory': 'joy', 'defeat': 'porajoy',
  'surrender': 'atmasamorpon',
  'success': 'safollyo', 'failure': 'byartha',
  'security': 'nirok', 'safety': 'nirok',
  'danger': 'bhoy', 'threat': 'bhoy',
  'attack': 'akraman', 'defense': 'rokkha', 'protection': 'rokkha',
  'created': 'toiri koreche',
  'established': 'sthapito',
  'formed': 'gothito',
  'called': 'bole', 'known as': 'naame porichito',
  'used': 'byabohrto', 'using': 'byabohar kore',
  'began': 'shuru', 'started': 'shuru',
  'ended': 'shesh',
  'emerged': 'utheche',
  'destroyed': 'noshtho',
  'affected': 'prabhabito', 'influenced': 'prabhabito',
  'transformed': 'rupantor',
  'became': 'hoye',
  'showed': 'dekhache',
  'argued': 'jukti koreche',
  'claimed': 'dabi koreche',
  'believed': 'bishwas koreto',
  'wanted': 'chaito',
  'failed': 'byartha',
  'won': 'jiteche', 'lost': 'hareche',
  'fought': 'juddho koreche',
  'killed': 'hatya kora hoyeche',
  'captured': 'bondi',
  'liberated': 'mukto', 'freed': 'mukto',
  'occupied': 'dojol', 'controlled': 'niyontrito',
  'ruled': 'rajotto koreche',
  'understood': 'bojha',
  'accepted': 'grohon', 'rejected': 'protyakhan',
  'global': 'bishwbapi', 'international': 'antojatik',
  'national': 'jatiyo', 'regional': 'anchalik',
  'local': 'sthaniyo', 'domestic': 'deshiyo',
  'foreign': 'bideshi',
  'central': 'kendriyo', 'eastern': 'purbo',
  'western': 'pashchim', 'northern': 'uttor', 'southern': 'dokkhin',
  'free': 'mukto', 'independent': 'swatantra', 'sovereign': 'sorbobhoum',
  'autonomous': 'swayottoshashit',
  'unstable': 'osthir', 'stable': 'sthir',
  'developed': 'unnoto', 'developing': 'unnoyonshil',
  'secularism': 'dhormoniropekota',
  'blasphemy': 'dhormiya apaman',
  'genocide': 'jonosonghar',
  'atrocities': 'nirjaton',
  'massacre': 'hatyakando',
  'terror': 'shonkho',
  'gdp': 'GDP',
  'trade': 'byobosah', 'export': 'roftani', 'import': 'amdat',
  'debt': 'rin', 'loan': 'rin',
  'investment': 'biniyog', 'capital': 'muddhon',
  'market': 'bajar', 'industry': 'shilpo',
  'poverty': 'doridrota', 'corruption': 'durodorshon',
  'infrastructure': 'obokathamo',
  'revenue': 'rajsob', 'tax': 'kor',
  'finance': 'ortho byabostha',
  'resources': 'sompod', 'sector': 'khondro',
  'area': 'onchol', 'region': 'onchol',
  'part': 'angsho', 'section': 'onsho',
  'analysis': 'bishleshon',
  'idea': 'dharona', 'concept': 'dharona',
  'view': 'dristibhongi', 'opinion': 'motamot',
  'perspective': 'dristibhongi',
  'argument': 'jukti', 'debate': 'bitorko',
  'discussion': 'alochona', 'conversation': 'kothabarta',
  'narrative': 'golpo', 'story': 'golpo',
  'source': 'utsho', 'data': 'tothy', 'information': 'tathyo',
  'knowledge': 'gyan', 'understanding': 'bujha',
  'truth': 'sotyo', 'fact': 'tothya',
  'reality': 'bastobota', 'real': 'ashol',
  'education': 'shikkha', 'science': 'biggan', 'scientific': 'boigganik',
  'technology': 'projukti',
  'news': 'khobor', 'media': 'gonomaddhom',
  'interview': 'shakkhatkar',
  'diplomatic': 'koutonitik', 'diplomacy': 'koutonityo',
  'treaty': 'chukti', 'agreement': 'shomjota',
  'alliance': 'jot',
  'relation': 'somporko', 'relationship': 'somporko',
  'cooperation': 'sahojogita',
  'weapon': 'ostro', 'arms': 'ostro',
  'nuclear': 'paramanu',
  'missile': 'kshepni astro',
  'air force': 'biman bahin', 'navy': 'nou bahin',
  'troops': 'sainik', 'forces': 'shokti',
  'intelligence': 'guptobhoktik',
  'surveillance': 'noyrona',
  'operation': 'porichalon',
  'campaign': 'abhijan',
  'offensive': 'akraman', 'defensive': 'rokkhamulok',
  'invasion': 'akraman',
  'ceasefire': 'juddho biram',
  'refugee': 'sorbashmoy',
  'bay of bengal': 'Bangal Uposhagor',
  'river': 'nodi', 'sea': 'shagor',
  'city': 'nagori', 'village': 'gram',
  'capital': 'rajdhani', 'port': 'bondor',
  'targeted': 'target kora',
  'creating': 'toiri kore',
  'built': 'toiri',
  'provided': 'pradan koreche',
  'provides': 'pradan kore',
  'providing': 'pradan korche',
  'largely': 'beshiram',
  'closely': 'ghonistho bhabe',
  'deeply': 'gobhir bhabe',
  'heavily': 'prabhob bhabe',
  'heavily': 'prabhob bhabe',
  'significantly': 'guruttopurno bhabe',
  'dramatically': 'natokiyo bhabe',
  'sharply': 'tikshno bhabe',
  'rapidly': 'drutotar sathe',
  'quickly': 'dhrutotar sathe',
  'slowly': 'dhire dhire',
  'constantly': 'nioto',
  'continually': 'niyomito',
  'aggressively': 'akramonmulok bhabe',
  'violently': 'himshratmak bhabe',
  'brutally': 'nisthur bhabe',
  'systematically': 'niyomito bhabe',
  'deliberately': 'icchakrit bhabe',
  'actively': 'sakriyo bhabe',
  'passively': 'nishkriyo bhabe',
  'illegally': 'ain birodhi bhabe',
  'officially': 'sorkari bhabe',
  'secretly': 'gopone',
  'openly': 'khola bhabe',
  'publicly': 'jonno samne',
  'privately': 'byaktigoto bhabe',
  'finally': 'sheshe',
  'eventually': 'sheshe',
  'immediately': 'turonto',
  'suddenly': 'hathat',
  'regularly': 'niomito',
  'frequently': 'prochur',
  'often': 'prochur',
  'usually': 'sadharonto',
  'sometimes': 'kokhono',
  'rarely': 'kom',
  'never': 'kokhono na',
  'always': 'sob somoy',
  'currently': 'bortoman',
  'previously': 'age',
  'recently': 'samprotik',
  'originally': 'muloto',
  'essentially': 'muloto',
  'basically': 'muloto',
  'completely': 'puro bhabe',
  'entirely': 'sompurno bhabe',
  'totally': 'puro bhabe',
  'absolutely': 'ekebarei',
  'nearly': 'pray', 'almost': 'pray',
  'approximately': 'prochur',
  'exactly': 'thik',
  'precisely': 'thik thik',
  'however': 'kintu',
  'therefore': 'tai',
  'thus': 'tai',
  'hence': 'tai',
  'meanwhile': 'ei somoy',
  'moreover': 'tarmadhye',
  'furthermore': 'aro',
  'nevertheless': 'tou',
  'nonetheless': 'tou',
  'although': 'jodio',
  'though': 'jodio',
  'despite': 'sottbeo',
  'regardless': 'nirapekhho',
  'whether': 'ki na',
  'after all': 'shesh porjonto',
  'secondly': 'ditiyoto',
  'thirdly': 'tritiyoto',
  'firstly': 'prothomoto',
  'finally': 'sheshe',
  'lastly': 'sheshe',
  'in addition': 'tarmadhye',
  'of course': 'oboshshoi',
  'per cent': 'shotansho',
  'per cent of': 'shotansho',
  'three-quarters': 'tin-char ansho',
  'half': 'ardhek',
  'quarter': 'ektu',
  'decades': 'dosok',
  'century': 'shotok',
  'one of the most': 'sobcheye',
  'one of the': 'ekti',
  'some of the': 'kono',
  'most of the': 'beshi',
  'many of the': 'onek',
  'few of the': 'kom',
  'rest of the': 'baki',
  'rest of': 'baki',
  'part of': 'angsho',
  'parts of': 'angsho',
  'number of': 'shongkhya',
  'lot of': 'onek',
  'lots of': 'onek',
  'plenty of': 'porejonto',
  'sort of': 'prokar',
  'type of': 'prokar',
  'kind of': 'prokar',
  'way of': 'upay',
  'lack of': 'abhab',
  'sense of': 'anubhob',
  'matter of': 'bishoy',
  'question of': 'proshno',
  'issue of': 'bishoy',
  'problem of': 'shomosya',
  'idea of': 'dharona',
  'act of': 'kaj',
  'use of': 'byabohar',
  'role of': 'bhumika',
  'form of': 'roop',
  'right of': 'odhikar',
  'set of': 'set',
  'point of view': 'dristibhongi',
  'in spite of': 'sottbeo',
  'because of': 'karone',
  'in front of': 'samne',
  'in terms of': 'dike theke',
  'in case of': 'kshetre',
  'on behalf of': 'paksh theke',
  'by means of': 'madhyome',
};

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function translate(text) {
  // Sort by length descending to match longer phrases first
  const entries = Object.entries(dict).sort((a, b) => b[0].length - a[0].length);

  let result = text;
  for (const [en, bn] of entries) {
    const regex = new RegExp('\\b' + escapeRegex(en) + '\\b', 'gi');
    result = result.replace(regex, bn);
  }
  return result;
}

function translateHtml(html) {
  const parts = html.split(/(<[^>]*>)/);
  return parts.map(p => p.startsWith('<') ? p : translate(p)).join('');
}

const newBanglaBody = eb.bangla;
const newFineBody = eb.fine;

bl.pages.bangla.body = translateHtml(newBanglaBody);
bl.pages.fine.body = translateHtml(newFineBody);

fs.writeFileSync('C:/Users/roika/Desktop/BaseVV/hoved/locales/bl.json', JSON.stringify(bl, null, 2), 'utf8');
console.log('Updated bl.json successfully');
